name: Deploy to GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        persist-credentials: false
        
    - name: Install 
      run: |
          npm install
          npm run build
      env:
        VUE_APP_CLIENT_ID: ${{ secrets.ID_CLIENT }}
        VUE_APP_API_KEY: ${{ secrets.API_KEY }}
        
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: dist
